hw/rtl/top/nsi_cp_top.sv
hw/rtl/clkreset/reset_sync.sv
hw/rtl/clkreset/clkgen.sv
hw/rtl/host/dma_engine.sv
hw/rtl/host/pcie_cxl_endpoint.sv
hw/rtl/fsm/fsm_pipeline.sv
hw/rtl/fsm/fsm_pattern_counter.sv
hw/rtl/fsm/fsm_canonical_label.sv
hw/rtl/gmf/gmf_pim_alu.sv
hw/rtl/gmf/gmf_banks_cluster.sv
hw/rtl/gmf/gmf_bank.sv
hw/rtl/common/axi4s_pkg.sv
hw/rtl/common/noc_pkg.sv
hw/rtl/common/axi4l_pkg.sv
hw/rtl/common/util_pkg.sv
hw/rtl/common/axi4l_dec_2to1.sv
hw/rtl/gse/gse_ingress_dma.sv
hw/rtl/gse/gse_activation_decoder.sv
hw/rtl/gse/gse_window_buffer.sv
hw/rtl/gse/gse_island_builder.sv
hw/rtl/mc/mc_riscv_subsys.sv
hw/rtl/mc/mc_axi_regs.sv
hw/rtl/noc/noc_bridge_axi4l.sv
hw/rtl/noc/noc_router.sv
hw/rtl/noc/noc_bridge_axi4s.sv
hw/rtl/pta/pta_pe.sv
hw/rtl/pta/pta_maskgen.sv
hw/rtl/pta/pta_scheduler.sv
